apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-jobmanager
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: ui
    port: 8081
{{- if .Values.jobmanager.haPort }}
  - name: ha
    port: {{ .Values.jobmanager.haPort }}
{{- end }}
  selector:
    app: {{ template "fullname" . }}
    component: jobmanager
