apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-jobmanager
spec:
  replicas: {{ .Values.flink.num_jobmanagers }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: jobmanager
  serviceName: {{ template "fullname" . }}-jobmanager-headless
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
{{- if .Values.jobmanager.haPort }}
        - containerPort: {{ .Values.jobmanager.haPort }}
          name: ha
{{- end }}          
        env:
        - name: FLINK_CONF_DIR
          value: /etc/flink
{{ if .Values.jobmanager.extraEnv }}
{{ toYaml .Values.jobmanager.extraEnv | indent 8 }}
{{ end }} 
        livenessProbe:
          httpGet:
            path: /overview
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
{{ toYaml .Values.jobmanager.resources | indent 10 }}
        volumeMounts:
        - name: {{ template "fullname" . }}-flink-config
          mountPath: /etc/flink
        - name: {{ template "fullname" . }}-hadoop-config
          mountPath: /etc/hadoop/conf
{{ if .Values.jobmanager.extraVolumeMounts }}
{{ toYaml .Values.jobmanager.extraVolumeMounts | indent 8 }}
{{ end }}      
{{ if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{ end }}
      volumes:
      - name: {{ template "fullname" . }}-flink-config
        configMap:
          name: {{ template "fullname" . }}-flink-config
      - name: {{ template "fullname" . }}-hadoop-config
        configMap:
          name: {{ template "fullname" . }}-hadoop-config
{{ if .Values.jobmanager.extraVolumes }}
{{ toYaml .Values.jobmanager.extraVolumes | indent 6 }}
{{ end }}